apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: r2qdapr-pubsub
  namespace: r2q
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://172.18.0.9:5672"
  - name: durable
    value: "false"
  - name: deletedWhenUnused
    value: "false"
  - name: autoAck
    value: "false"
  - name: reconnectWait
    value: "0"
  - name: concurrency
    value: parallel
scopes:
  - r2q-service1
  - r2q-service2
  - r2q-service3
