apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: config
  namespace: default
spec:
  tracing:  
    enabled: true
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://172.18.0.8:9411/api/v2/spans" #zipkin container ip 172.18.0.5